# Generated by Django 4.2.6 on 2023-11-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_appuser_date_joined_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
