# Generated by Django 4.2.7 on 2023-11-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
