# Generated by Django 4.2.7 on 2023-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='timeslot',
            field=models.ManyToManyField(db_constraint=False, to='timetable.timeslot'),
        ),
    ]
