# Generated by Django 4.2.7 on 2023-11-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_lesson_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonNr',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
