# Generated by Django 4.2.7 on 2023-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='information',
            field=models.ManyToManyField(blank=True, null=True, to='timetable.information'),
        ),
    ]
