# Generated by Django 4.2.7 on 2023-11-12 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0013_remove_document_rooms_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(choices=[('MI', 'Medieninformatik'), ('AI', 'Angewandte Informatik'), ('WI', 'Wirtschafts Informatik'), ('TS', 'Technische Systeme')], max_length=46)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MO', 'Montag'), ('DI', 'Dienstag'), ('MI', 'Mittwoch'), ('DO', 'Donnerstag'), ('FR', 'Freitag'), ('SA', 'Samstag'), ('SO', 'Sonntag')], max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimetableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=45)),
                ('file_data', models.FileField(upload_to='store/timetables/')),
                ('semester_start', models.DateField()),
                ('semester_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNr', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('building', models.CharField(blank=True, max_length=20, null=True)),
                ('beamer', models.CharField(blank=True, max_length=180, null=True)),
                ('courses', models.ManyToManyField(to='timetable.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNr', models.IntegerField()),
                ('lessonName', models.CharField(max_length=120)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('typ', models.CharField(choices=[('V', 'Vorlesung'), ('P', 'Praktikum'), ('Ü', 'Übung'), ('S', 'Seminar')], max_length=1)),
                ('group', models.CharField(blank=True, max_length=2, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
                ('information', models.ManyToManyField(blank=True, null=True, to='timetable.information')),
                ('room', models.ManyToManyField(to='timetable.room')),
                ('teacher', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ManyToManyField(db_constraint=False, to='timetable.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentData', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('rooms', models.ManyToManyField(to='timetable.room')),
            ],
        ),
    ]
