# Generated by Django 4.2.7 on 2023-11-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='document',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='information',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='room',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='room',
            name='courses',
        ),
        migrations.DeleteModel(
            name='TimetableModel',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
