# Generated by Django 4.2.7 on 2023-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='onlyDisplay',
            field=models.BooleanField(default=False),
        ),
    ]
