# Generated by Django 4.2.7 on 2023-11-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_alter_information_end_alter_information_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableModel',
        ),
    ]
