# Generated by Django 4.2.7 on 2023-11-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_delete_timetablemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=45)),
                ('timetable_data', models.FileField(upload_to='timetables/')),
                ('semester_start', models.DateField()),
                ('semester_end', models.DateField()),
            ],
        ),
    ]
