# Generated by Django 4.2.7 on 2023-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0029_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamer',
            name='port',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
