# Generated by Django 4.2.7 on 2023-11-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='semester_timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.semestertimetable'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.study'),
        ),
    ]
